# Generated by Django 2.2 on 2019-05-03 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190502_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='counsellor1',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'counsellor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
