# Generated by Django 2.2 on 2019-05-21 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(choices=[(datetime.time(8, 0), '7-8 AM'), (datetime.time(9, 0), '8-9 AM'), (datetime.time(10, 0), '9-10 AM'), (datetime.time(11, 0), '10-11 AM'), (datetime.time(12, 0), '11-12 PM'), (datetime.time(13, 0), '12-1 PM'), (datetime.time(14, 0), '1-2 PM'), (datetime.time(15, 0), '2-3 PM'), (datetime.time(16, 0), '3-4 PM')], max_length=100),
        ),
    ]
