# Generated by Django 2.2 on 2019-05-21 03:08

import booking.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190521_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8-9 AM'), (datetime.time(9, 0), '9-10 AM'), (datetime.time(10, 0), '10-11 AM'), (datetime.time(11, 0), '11-12 PM'), (datetime.time(12, 0), '12-1 PM'), (datetime.time(13, 0), '1-2 PM'), (datetime.time(14, 0), '2-3 PM'), (datetime.time(15, 0), '3-4 PM')], validators=[booking.validators.validate_time]),
        ),
    ]
