# Generated by Django 2.2 on 2019-05-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmation',
            old_name='counsellor',
            new_name='counsellor1',
        ),
        migrations.RenameField(
            model_name='confirmation',
            old_name='students_name',
            new_name='username',
        ),
    ]
