# Generated by Django 2.2 on 2019-05-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20190526_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='counsellor1',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'counsellor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counsellors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
