# Generated by Django 2.2 on 2019-06-03 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20190602_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'normal'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
