# Generated by Django 2.2 on 2019-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20190625_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
    ]
