# Generated by Django 2.2 on 2019-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(default=0, help_text='should be in form of e.g S11/15333/18', max_length=255, null=True, unique=True),
        ),
    ]
